### PR TITLE
WASM version of Refactor Animation System.

### PR DESCRIPTION
**Pull request by gonnavis**
Follow: https://github.com/webaverse/app/pull/3116
Sibling PR: https://github.com/upstreet-labs/app/pull/82

## Simple usage example:
In this example we'll adding a "magic idle" animation into the animation tree.

- On js side, make sure the new animation `.fbx` file, such as `magic standing idle.fbx`, added to `app\public\animations` folder and successfully ran `node animations-baker.mjs`.

- Add a `magicState` parameter into `updateAvatar()` function, it'll be used to control the playing of "magic idle" animation.
```
physx.physxWorker.updateAvatar(avatar.animationAvatarPtr, [
  // ...
  avatar.magicState,
  // ...
]);
```

- On wasm side, create a `motion` called `magicStandingIdle`.
And, optionally, set its speed.
```
this->motiono["magicStandingIdle"] = this->mixer->createMotion(animationo["magic standing idle.fbx"], "magicStandingIdle");
// this->motiono["magicStandingIdle"]->setSpeed(1.7); // optional
```

- Create a `node` called `magicNodeTwo`.
Add previous node as it's first child.
Add new `magicStandingIdle` motion as second child.
```
this->nodeo["magicNodeTwo"] = this->mixer->createNode(NodeType::TWO, "magicNodeTwo");
this->nodeo["magicNodeTwo"]->addChild(this->nodeo["holdNodeFunc"]);
this->nodeo["magicNodeTwo"]->addChild(this->motiono["magicStandingIdle"]);
```

- Set `magicNodeTwo` node as root node.
```
this->mixer->setRootNode(this->nodeo["magicNodeTwo"]);
```

- Add a `magicState` parameter into `Avatar::update()` function, the order must be exactly the same as the js side.
```
void Avatar::update(float *scratchStack)
{
  // action states ---
  // ...
  bool magicState = scratchStack[index++];
  // ...
}
```

- Add `magicStart`, `magicEnd` and `lastMagicState` declarations into `class Avatar`.
```
class Avatar
{
public:
  // action start/end events
  // ...
  bool magicStart, magicEnd, lastMagicState;
  // ...
}
```

- Add `magicStart` and `magicEnd` checking logics into `Avatar::update()` function.
```
void Avatar::update(float *scratchStack)
{
  // set start/end events ---
  // ...
  this->magicStart = false;
  this->magicEnd = false;
  if (magicState != this->lastMagicState)
  {
    if (magicState) this->magicStart = true;
    else this->magicEnd = true;
  }
  this->lastMagicState = magicState;
  // ...
}
```

- Add `crossFade()` functions into `Avatar::update()` function.
  `crossFade()` for `end` event need run before the one for `start` event.
```
void Avatar::update(float *scratchStack)
{
  // action end events ---
  // ...
  if (this->magicEnd) {
    this->nodeo["magicNodeTwo"]->crossFadeTwo(0.2, 0);
  }
  // ...

  // action start events ---
  // ...
  if (this->magicStart) {
    this->nodeo["magicNodeTwo"]->crossFadeTwo(0.2, 1);
  }
  // ...
}
```

- Compile wasm and copy/paste the result built files into `app` repo.

- OK, now if the `magicState` changed on js side ( true <-> false ), the `magic idle` animation will play/stop accordingly.
  Add has transitions between different animations added automatically.

https://user-images.githubusercontent.com/10785634/190175673-668bed35-e455-41dd-b3d0-6a1831bfacea.mp4

Reference codes:
https://github.com/upstreet-labs/app/commit/1eb950d82aa87ad24443de8615e65b3a0a9fc7c1
https://github.com/webaverse/app-wasm/commit/908632aa76895e95ca5754aa17c66e28902e9efb

## Doc:
Now only has outdated js version doc https://github.com/webaverse/app/pull/3116 , but the basic thinking is the same.
Will update to new wasm version.

### CODE REVIEW

**Review by avaer — APPROVED** [review]

**Review by avaer — APPROVED** [review]

**Comment by gonnavis** [comment]
- Start from and return to current crouch animation

15 npcs ( with 300 Hz monitor ):
js: ~ 90 fps            | wasm: ~ 110 fps
:-------------------------:|:-------------------------:
image   | image

200 loop:
js: ~ 25 fps            | wasm: ~ 50 fps
:-------------------------:|:-------------------------:
image   | image

**Comment by avaer** [comment]
Awesome improvement!

> I encountered gltfLoader error with more npcs, so 15 npcs for now.
We will need to fix that. It shouldn't error, especially if the same avatars are being loaded (should be hitting the same caches).

**Comment by gonnavis** [comment]
Testing through 5 seconds performance profile:

js: 47.4ms 1.3%, 617.3ms 16.4%.
image

wasm: 13.1ms 0.5%, 169.4ms 6.8%.
image

Also proved wasm version's performance is better.
One big cause should be the `slerpFlat` function transferred from js side to wasm side.

**Comment by gonnavis** [comment]
Close in favor of https://github.com/webaverse/app-wasm/pull/75

**Pull request closed without merging**
